/* No networking. All amounts are integer euro cents. */
export const RETENTION_DAYS=90;
export const CATEGORIES=[
 {id:'groceries',name:'Lebensmittel',color:'#3b65ce',fixed:false},
 {id:'housing',name:'Wohnen',color:'#17253f',fixed:true},
 {id:'utilities',name:'Energie & Internet',color:'#6d54a6',fixed:true},
 {id:'transport',name:'Mobilität',color:'#228183',fixed:false},
 {id:'health',name:'Gesundheit',color:'#bd5364',fixed:false},
 {id:'insurance',name:'Versicherungen',color:'#536783',fixed:true},
 {id:'leisure',name:'Freizeit & Essen gehen',color:'#aa6824',fixed:false},
 {id:'shopping',name:'Haushalt & Einkäufe',color:'#876147',fixed:false},
 {id:'subscriptions',name:'Abos',color:'#6655be',fixed:true},
 {id:'other',name:'Sonstiges',color:'#697386',fixed:false},
 {id:'income',name:'Einnahmen',color:'#23724d',fixed:false}
];
export const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export function validDate(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===s&&s>='1900-01-01'&&s<='2199-12-31';}
export function shiftDay(day,delta){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+delta);return d.toISOString().slice(0,10);}
export const monthOf=s=>s.slice(0,7);
export function parseDate(text,year){const m=String(text).match(/^(\d{2})\.(\d{2})\.(\d{4}|\d{2})?$/);if(!m)return null;let y=m[3]||year;if(!y)return null;if(String(y).length===2)y='20'+y;const s=`${y}-${m[2]}-${m[1]}`;return validDate(s)?s:null;}
export function parseMoney(text){let s=String(text).trim().replace(/[€\s\u00a0]/g,'').replace(/Euro|EUR/gi,'').replace(/[−–]/g,'-');let neg=s.startsWith('-')||s.endsWith('-');s=s.replace(/^[-+]|[-+]$/g,'');if(!/^(?:\d{1,3}(?:\.\d{3})+|\d+)(?:,\d{1,2})?$/.test(s))throw Error('Betrag bitte im Format 123,45 eingeben.');const [eu,ct='']=s.split(','),c=Number(eu.replaceAll('.',''))*100+Number(ct.padEnd(2,'0'));if(!Number.isSafeInteger(c)||c>1e12)throw Error('Betrag liegt außerhalb des unterstützten Bereichs.');return neg?-c:c;}
export const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n/100);
export const inputMoney=n=>(Math.abs(n)/100).toFixed(2).replace('.',',');
export const monthLabel=m=>new Date(m+'-15T12:00:00').toLocaleDateString('de-DE',{month:'long',year:'numeric'});
export const uid=()=>crypto.randomUUID();
export function cleanDescription(text){return String(text).replace(/\b[A-Z]{2}\d{2}(?:\s?[A-Z0-9]){11,30}\b/g,'[IBAN entfernt]').replace(/\b(?:ARN|NR|KARTENNUMMER)\s*\d{6,}\b/gi,'').replace(/(?:Mandat|Mandatsreferenz|Gläubiger-ID|Referenz)\s*:.*$/gmi,'').replace(/\b\d{13,19}\b/g,'[Referenz entfernt]').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim().slice(0,1600);}
export function merchantOf(text){return cleanDescription(text).split('\n')[0].replace(/^(?:Lastschrift|Gutschrift|Überweisung|Dauerauftrag|Kartenzahlung|Bargeldauszahlung|Entgelt|Zinsgutschrift)\s*/i,'').replace(/^VISA\s*/i,'').trim().slice(0,100)||'Buchung';}
export function suggestCategory(text,cents){const s=text.toUpperCase();if(cents>=0)return 'income';for(const [re,id] of [[/ALDI|LIDL|REWE|EDEKA|KAUFLAND|NETTO|PENNY|SUPERMARKT/,'groceries'],[/MIETE|HAUSVERWALTUNG|WOHNUNG/,'housing'],[/STROM|GASABSCHLAG|STADTWERKE|TELEKOM|VODAFONE|O2 |INTERNET/,'utilities'],[/DEUTSCHE BAHN|DB VERTRIEB|TANKSTELLE|ARAL|SHELL|ÖPNV|DEUTSCHLANDTICKET/,'transport'],[/APOTHEKE|ARZT|ZAHNARZT/,'health'],[/VERSICHERUNG|ALLIANZ|HUK|DEBEKA/,'insurance'],[/RESTAURANT|CAF[EÉ]|PIZZA|KINO|BÄCKEREI/,'leisure'],[/NETFLIX|SPOTIFY|HALLOW|ABONNEMENT/,'subscriptions'],[/IKEA|BAUMARKT|DM-DROGERIE|ROSSMANN|AMAZON/,'shopping']])if(re.test(s))return id;return 'other';}
export function newBook(day=todayISO()){return {schema:1,id:uid(),generation:0,mode:'primary',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),retentionAsOf:day,categories:structuredClone(CATEGORIES),accounts:[{id:'main',name:'ING Girokonto'}],transactions:[],summaries:{},budgets:{},receipts:[],receiptKey:Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('')};}
export function validateBook(b){
 if(!b||b.schema!==1||typeof b.id!=='string'||!['primary','viewer'].includes(b.mode)||!Number.isSafeInteger(b.generation)||b.generation<0||!validDate(b.retentionAsOf))throw Error('Diese Datei enthält kein unterstütztes Haushaltsbuch.');
 if(!Array.isArray(b.categories)||!b.categories.length||b.categories.length>80||!Array.isArray(b.accounts)||!b.accounts.length||b.accounts.length>20||!Array.isArray(b.transactions)||b.transactions.length>100000||!Array.isArray(b.receipts)||b.receipts.length>300000)throw Error('Ungültige oder zu große Haushaltsbuch-Datei.');
 const safeId=s=>typeof s==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(s)&&!['__proto__','constructor','prototype'].includes(s),str=(s,max)=>typeof s==='string'&&s.length<=max;
 if(!b.categories.every(c=>safeId(c.id)&&str(c.name,80)&&/^#[a-f\d]{6}$/i.test(c.color))||new Set(b.categories.map(c=>c.id)).size!==b.categories.length)throw Error('Ungültige Kategorien.');
 if(!b.accounts.every(a=>safeId(a.id)&&str(a.name,80)))throw Error('Ungültige Konten.');
 const cats=new Set(b.categories.map(c=>c.id)),accs=new Set(b.accounts.map(a=>a.id));
 for(const t of b.transactions)if(!safeId(t.id)||!validDate(t.date)||!Number.isSafeInteger(t.cents)||Math.abs(t.cents)>1e12||!str(t.merchant,160)||!str(t.description,2000)||!cats.has(t.category)||!accs.has(t.account)||!['expense','income','refund','transfer'].includes(t.kind)||(t.kind==='expense'&&t.cents>0)||(['income','refund'].includes(t.kind)&&t.cents<0))throw Error('Ungültige Buchung in der Datei.');
 if(new Set(b.transactions.map(t=>t.id)).size!==b.transactions.length)throw Error('Doppelte Buchungskennungen.');
 if(!b.summaries||typeof b.summaries!=='object'||Array.isArray(b.summaries)||!b.budgets||typeof b.budgets!=='object'||Array.isArray(b.budgets))throw Error('Ungültige Monatsdaten.');
 for(const [m,items] of Object.entries(b.summaries)){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(m)||!Array.isArray(items)||items.length>400)throw Error('Ungültige Monatsdaten.');for(const x of items)if(!cats.has(x.category)||!['expense','income','refund','transfer'].includes(x.kind)||!Number.isSafeInteger(x.cents)||Math.abs(x.cents)>1e14||!Number.isSafeInteger(x.count)||x.count<1)throw Error('Ungültige Monatssummen.');}
 for(const [m,v] of Object.entries(b.budgets)){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(m)||!v||typeof v!=='object'||Array.isArray(v))throw Error('Ungültiges Budget.');for(const [k,n] of Object.entries(v))if(!cats.has(k)||!Number.isSafeInteger(n)||n<0||n>1e12)throw Error('Ungültiges Budget.');}
 if(!/^[a-f\d]{64}$/.test(b.receiptKey)||!b.receipts.every(x=>typeof x==='string'&&/^[a-f\d]{64}$/.test(x)))throw Error('Ungültige Import-Prüfcodes.');return b;
}
function summarize(b,t){const month=monthOf(t.date),items=b.summaries[month]??(b.summaries[month]=[]);let row=items.find(x=>x.category===t.category&&x.kind===t.kind);if(!row){row={category:t.category,kind:t.kind,cents:0,count:0};items.push(row);}row.cents+=t.cents;row.count++;}
export function compactBook(b,day=todayISO(),all=false){const safeDay=day>b.retentionAsOf?day:b.retentionAsOf,cutoff=shiftDay(safeDay,-RETENTION_DAYS),keep=[];let count=0;for(const t of b.transactions){if(all||t.date<=cutoff){summarize(b,t);count++;}else keep.push(t);}b.transactions=keep;b.retentionAsOf=safeDay;return count;}
export function totals(b,month){const cats=Object.fromEntries(b.categories.map(c=>[c.id,{expense:0,income:0,refund:0,count:0}]));let transfers=0;const include=x=>{if(x.kind==='transfer'){transfers+=x.cents;return;}const r=cats[x.category];if(!r)return;r.count+=x.count??1;if(x.kind==='expense')r.expense+=-x.cents;else if(x.kind==='refund')r.refund+=x.cents;else r.income+=x.cents;};(b.summaries[month]||[]).forEach(include);b.transactions.filter(t=>monthOf(t.date)===month).forEach(include);const values=Object.values(cats),income=values.reduce((s,c)=>s+c.income,0),gross=values.reduce((s,c)=>s+c.expense,0),refunds=values.reduce((s,c)=>s+c.refund,0);return {cats,income,gross,refunds,expense:gross-refunds,balance:income-gross+refunds,transfers,count:values.reduce((s,c)=>s+c.count,0)};}
export function allMonths(b){const next=new Date(todayISO()+'T12:00:00');next.setDate(1);next.setMonth(next.getMonth()+1);const following=`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}`;return [...new Set([following,todayISO().slice(0,7),...b.transactions.map(t=>monthOf(t.date)),...Object.keys(b.summaries),...Object.keys(b.budgets)])].sort().reverse();}
export function snapshot(b,details=false){const copy=structuredClone(b);compactBook(copy);if(!details)compactBook(copy,todayISO(),true);copy.mode='viewer';copy.receipts=[];copy.receiptKey='0'.repeat(64);return copy;}
export async function fingerprints(rows,book,account){const bytes=Uint8Array.from(book.receiptKey.match(/../g),x=>parseInt(x,16)),key=await crypto.subtle.importKey('raw',bytes,{name:'HMAC',hash:'SHA-256'},false,['sign']),counter=new Map();bytes.fill(0);const seen=new Set(book.receipts);for(const row of rows){const base=[account,row.date,row.cents,(row.sourceText||row.description||row.merchant).normalize('NFKC').replace(/\s+/g,' ').trim().toUpperCase()].join('|'),n=(counter.get(base)||0)+1;counter.set(base,n);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(base+'|'+n));row.fingerprint=Array.from(new Uint8Array(sig),x=>x.toString(16).padStart(2,'0')).join('');row.duplicate=seen.has(row.fingerprint);row.selected=!row.duplicate;row.account=account;delete row.sourceText;}return rows;}
export function commitRows(book,rows,day=todayISO()){const seen=new Set(book.receipts);let added=0,duplicates=0;for(const r of rows){if(!r.selected)continue;if(r.fingerprint&&seen.has(r.fingerprint)&&!r.force){duplicates++;continue;}if(!validDate(r.date)||!Number.isSafeInteger(r.cents)||Math.abs(r.cents)>1e12||!book.categories.some(c=>c.id===r.category)||!book.accounts.some(a=>a.id===r.account))throw Error('Bitte alle ausgewählten Buchungen prüfen.');const kind=r.kind|| (r.cents<0?'expense':'income');if((kind==='expense'&&r.cents>=0)||(['income','refund'].includes(kind)&&r.cents<0))throw Error('Buchungsart und Vorzeichen passen nicht zusammen.');book.transactions.push({id:uid(),date:r.date,cents:r.cents,merchant:String(r.merchant||'Buchung').slice(0,160),description:cleanDescription(r.description||''),category:r.category,kind,account:r.account});if(r.fingerprint)seen.add(r.fingerprint);added++;}book.receipts=[...seen];const compacted=compactBook(book,day);return {added,duplicates,compacted};}
