import {parseDate,parseMoney,merchantOf,cleanDescription,suggestCategory} from './core.js';
const AMOUNT=/(?<![\d.,])([+−–-]?\s*(?:\d{1,3}(?:\.\d{3})+|\d+),\d{2}\s*(?:€|Euro|EUR)?\s*[-+]?)\s*$/i;
const DATE=/^(\d{2}\.\d{2}\.(?:\d{4}|\d{2})?)(?:\s+|$)/;
const FOOT=/^(?:ING(?:-DiBa)?\b|Seite\s+\d|Buchung\s*(?:Valuta|Buchung)|Valuta\s*(?:Buchung|Betrag)|Betrag\s*\(EUR\)|Girokonto\b|IBAN\b|BIC\b|Kontoauszug\b|Konto-Nr|Kontonummer|Kunden-Information|Bitte beachten|Herrn?\b|Frau\b|\d{5}\s+[A-ZÄÖÜ]|Vorstand\b|Vorsitzender\b|Sitz\b|Mitglied im\b|USt|Steuernummer|Handelsregister|www\.ing|Internet:|E-Mail:|Ihr Dispositionskredit)/i;
export function linesFromItems(items){const rows=[];for(const i of items){if(!i.str?.trim()||!i.transform)continue;const y=i.transform[5],x=i.transform[4];let row=rows.find(r=>Math.abs(r.y-y)<2.5);if(!row){row={y,items:[]};rows.push(row);}row.items.push({x,text:i.str});}return rows.sort((a,b)=>b.y-a.y).map(r=>r.items.sort((a,b)=>a.x-b.x).map(i=>i.text).join(' ').replace(/\s+/g,' ').trim());}
export function parseStatement(input,{year=new Date().getFullYear()}={}){
 const lines=(Array.isArray(input)?input:String(input).split(/\r?\n/)).map(x=>String(x).replace(/\u00a0/g,' ').trim()).filter(Boolean),all=lines.join('\n'),headerYear=all.match(/Kontoauszug[^\n]*\b(20\d{2})\b/i)?.[1];if(headerYear)year=headerYear;
 const rows=[],warnings=[];let opening=null,closing=null,current=null,unparsed=0;
 function finish(){if(!current)return;if(current.cents===null){unparsed++;current=null;return;}const description=cleanDescription(current.parts.join('\n')),merchant=merchantOf(description);rows.push({date:current.date,cents:current.cents,merchant,description,sourceText:current.parts.join(' '),category:suggestCategory(description,current.cents),kind:current.cents<0?'expense':'income',needsReview:current.inferred,selected:true});current=null;}
 for(const line of lines){
  if(/(?:Alter|Alte[rn]?|Anfangs)\s*(?:Saldo|Kontostand)|Anfangssaldo/i.test(line)){const m=line.match(AMOUNT);if(m)try{opening=parseMoney(m[1]);}catch{}finish();continue;}
  if(/(?:Neuer|Neue[rn]?|End)\s*(?:Saldo|Kontostand)|Endsaldo/i.test(line)){const m=line.match(AMOUNT);if(m)try{closing=parseMoney(m[1]);}catch{}finish();continue;}
  if(FOOT.test(line)){if(/Kunden-Information|Vorstand|Bitte beachten/.test(line))finish();continue;}
  const dm=line.match(DATE);let rest=dm?line.slice(dm[0].length).trim():line;
  if(dm){const second=rest.match(DATE);if(second)rest=rest.slice(second[0].length).trim();const am=rest.match(AMOUNT),date=parseDate(dm[1],year),content=am?rest.slice(0,am.index).trim():rest;
   if(date&&content&&am){finish();let cents;try{cents=parseMoney(am[1]);}catch{unparsed++;continue;}const signed=/[-+−–]/.test(am[1]);let inferred=false;if(!signed){if(/^(Lastschrift|Dauerauftrag|(?:Überweisung|Ueberweisung)|Entgelt|Kartenzahlung|Bargeld|Abbuchung)/i.test(content))cents=-Math.abs(cents);else if(/^(Gutschrift|Gehalt|Zinsgutschrift|Zinsertrag|Lohn)/i.test(content))cents=Math.abs(cents);else inferred=true;}current={date,cents,parts:[content],inferred};continue;}
   if(date&&content&&!am&&/^(Lastschrift|Gutschrift|(?:Überweisung|Ueberweisung)|Dauerauftrag|Entgelt|Kartenzahlung|Bargeld|Zins)/i.test(content)){finish();current={date,cents:null,parts:[content],inferred:true};continue;}
   if(date&&!rest)continue; // Date-only line is the separate ING value date.
   if(date&&current){current.parts.push(rest);continue;}
   if(date){unparsed++;continue;}
  }
  if(current){if(current.cents===null){const am=line.match(AMOUNT);if(am){try{let cents=parseMoney(am[1]);if(!/[-+−–]/.test(am[1])&&/^(Lastschrift|(?:Überweisung|Ueberweisung)|Dauerauftrag|Entgelt)/i.test(current.parts[0]))cents=-Math.abs(cents);current.cents=cents;}catch{}const before=line.slice(0,am.index).trim();if(before)current.parts.push(before);continue;}}if(current.parts.length<20)current.parts.push(line);}
 }
 finish();if(!/ING|ING-DiBa/i.test(all))warnings.push('Kein ING-Dokumentkopf erkannt. Bitte das Format und jede Buchung prüfen.');if(unparsed)warnings.push(`${unparsed} Zeilen mit Datum konnten nicht sicher zugeordnet werden.`);if(rows.some(r=>r.needsReview))warnings.push('Bei einzelnen Buchungen ist die Richtung unklar. Einnahme oder Ausgabe bitte prüfen.');if(!rows.length)warnings.push('Keine Buchungen erkannt. Du kannst Text einfügen oder Buchungen manuell ergänzen.');
 const net=rows.reduce((s,r)=>s+r.cents,0),reconciliation=opening!==null&&closing!==null?{opening,closing,net,difference:closing-opening-net}:null;if(reconciliation?.difference)warnings.push('Die erkannten Beträge stimmen nicht mit der Saldoänderung überein. Fehlende oder falsche Buchungen bitte korrigieren.');if(!reconciliation)warnings.push('Kein vollständiger Saldoabgleich möglich. Die Summe bitte mit dem Auszug vergleichen.');return {rows,warnings,reconciliation,unparsed};
}
export async function extractPDF(file,onProgress=()=>{},password=''){
 if(file.size>15*1024*1024)throw Error('Die PDF ist größer als 15 MB. Bitte einen kürzeren Auszug verwenden.');
 const bytes=new Uint8Array(await file.arrayBuffer());if(new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw Error('Bitte eine PDF-Datei auswählen.');
 let task;try{const pdfjs=await import('./vendor/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.mjs',import.meta.url).href;task=pdfjs.getDocument({data:bytes,password,isEvalSupported:false,disableFontFace:true,useSystemFonts:false,useWasm:false,isOffscreenCanvasSupported:false,isImageDecoderSupported:false,disableAutoFetch:true,stopAtErrors:true,verbosity:0});const pdf=await task.promise;if(pdf.numPages>80)throw Error('Maximal 80 Seiten pro Import. Bitte den Auszug aufteilen.');const lines=[];for(let n=1;n<=pdf.numPages;n++){onProgress(n,pdf.numPages);const page=await pdf.getPage(n);const content=await page.getTextContent();lines.push(...linesFromItems(content.items));page.cleanup();if(lines.length>60000)throw Error('Der Auszug enthält zu viele Textzeilen.');}if(!lines.length)throw Error('Kein kopierbarer Text gefunden. Gescannte PDFs werden nicht unterstützt.');return parseStatement(lines);}catch(e){if(e.name==='PasswordException')throw Error('Diese PDF benötigt ein eigenes PDF-Passwort. Bitte im Importfeld eintragen und erneut auswählen.');throw e;}finally{await task?.destroy();try{bytes.fill(0);}catch{}}
}
