const DB='centrala-budget-v1',STORE='vault',FORMAT='centrala-budget-encrypted',ITERATIONS=600000;
const enc=new TextEncoder(),dec=new TextDecoder();
const toB64=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);};
const fromB64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
export async function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('Der lokale Speicher ist nicht verfügbar. Bitte Safari außerhalb des privaten Modus verwenden.'));});}
export async function readVault(){const db=await openDB();try{return await new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get('main');r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);});}finally{db.close();}}
export async function saveVault(envelope,expectedRevision=null){const db=await openDB();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),store=tx.objectStore(STORE),get=store.get('main');let reason=null;get.onsuccess=()=>{const current=get.result?.revision??null;if(current!==expectedRevision){reason=Error('Das Haushaltsbuch wurde in einem anderen Fenster geändert. Bitte sperren und erneut öffnen.');tx.abort();return;}store.put(envelope,'main');};tx.oncomplete=()=>resolve(envelope.revision);tx.onabort=tx.onerror=()=>reject(reason||Error('Speichern fehlgeschlagen. Die Änderung wurde nicht übernommen. Speicherplatz und Browsermodus prüfen.'));});}finally{db.close();}}
export function validateEnvelope(v){if(!v||v.format!==FORMAT||v.version!==1||v.kdf!=='PBKDF2-SHA256'||v.iterations!==ITERATIONS||v.cipher!=='AES-256-GCM'||typeof v.salt!=='string'||typeof v.iv!=='string'||typeof v.data!=='string'||v.data.length>50*1024*1024||typeof v.revision!=='string')throw Error('Keine gültige verschlüsselte Budget-Datei.');try{if(fromB64(v.salt).length!==32||fromB64(v.iv).length!==12||fromB64(v.data).length<17)throw Error();}catch{throw Error('Die Budget-Datei ist beschädigt.');}return v;}
export async function deriveKey(password,salt){const bytes=enc.encode(password),base=await crypto.subtle.importKey('raw',bytes,'PBKDF2',false,['deriveKey']);bytes.fill(0);return crypto.subtle.deriveKey({name:'PBKDF2',salt:fromB64(salt),iterations:ITERATIONS,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
function aad(v){return enc.encode([v.format,v.version,v.kdf,v.iterations,v.cipher,v.salt,v.revision].join('|'));}
export async function seal(book,key,salt){const v={format:FORMAT,version:1,kdf:'PBKDF2-SHA256',iterations:ITERATIONS,cipher:'AES-256-GCM',salt,revision:crypto.randomUUID(),iv:toB64(crypto.getRandomValues(new Uint8Array(12))),data:''};const plain=enc.encode(JSON.stringify(book));try{v.data=toB64(new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:fromB64(v.iv),additionalData:aad(v),tagLength:128},key,plain)));return v;}finally{plain.fill(0);}}
export async function createVault(book,password){if(password.length<12||password.length>512)throw Error('Bitte mindestens 12 und höchstens 512 Zeichen verwenden.');const salt=toB64(crypto.getRandomValues(new Uint8Array(32))),key=await deriveKey(password,salt);return {envelope:await seal(book,key,salt),key,salt};}
export async function unlockVault(envelope,password){validateEnvelope(envelope);const key=await deriveKey(password,envelope.salt);let plain;try{plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64(envelope.iv),additionalData:aad(envelope),tagLength:128},key,fromB64(envelope.data)));const book=JSON.parse(dec.decode(plain));return {book,key,salt:envelope.salt};}catch{throw Error('Passwort falsch oder Datei beschädigt. Es wurde nichts verändert.');}finally{plain?.fill(0);}}
